// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;
pub const FEEDBACK: u8 = 0;
pub const ROSRUN: u8 = 1;
pub const ROSLAUNCH: u8 = 2;

extern "C" {
    fn visualization_msgs__msg__MenuEntry__init(msg: *mut MenuEntry) -> bool;
    fn visualization_msgs__msg__MenuEntry__fini(msg: *mut MenuEntry);
    fn visualization_msgs__msg__MenuEntry__are_equal(lhs: *const MenuEntry, rhs: *const MenuEntry) -> bool;
    fn visualization_msgs__msg__MenuEntry__Sequence__init(msg: *mut MenuEntrySeqRaw, size: usize) -> bool;
    fn visualization_msgs__msg__MenuEntry__Sequence__fini(msg: *mut MenuEntrySeqRaw);
    fn visualization_msgs__msg__MenuEntry__Sequence__are_equal(lhs: *const MenuEntrySeqRaw, rhs: *const MenuEntrySeqRaw) -> bool;
    fn rosidl_typesupport_c__get_message_type_support_handle__visualization_msgs__msg__MenuEntry() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct MenuEntry {
    pub id: u32,
    pub parent_id: u32,
    pub title: crate::msg::RosString<0>,
    pub command: crate::msg::RosString<0>,
    pub command_type: u8,
}

impl MenuEntry {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { visualization_msgs__msg__MenuEntry__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for MenuEntry {
    fn drop(&mut self) {
        unsafe { visualization_msgs__msg__MenuEntry__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct MenuEntrySeqRaw {
    data: *mut MenuEntry,
    size: usize,
    capacity: usize,
}

/// Sequence of MenuEntry.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct MenuEntrySeq<const N: usize> {
    data: *mut MenuEntry,
    size: usize,
    capacity: usize,
}

impl<const N: usize> MenuEntrySeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: MenuEntrySeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { visualization_msgs__msg__MenuEntry__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn null() -> Self {
        let msg: MenuEntrySeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        Self {data: msg.data, size: msg.size, capacity: msg.capacity }
    }

    pub fn as_slice(&self) -> &[MenuEntry] {
        if self.data.is_null() {
            &[]
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            s
        }
    }

    pub fn as_slice_mut(&mut self) -> &mut [MenuEntry] {
        if self.data.is_null() {
            &mut []
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            s
        }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, MenuEntry> {
        self.as_slice().iter()
    }

    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, MenuEntry> {
        self.as_slice_mut().iter_mut()
    }

    pub fn len(&self) -> usize {
        self.as_slice().len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<const N: usize> Drop for MenuEntrySeq<N> {
    fn drop(&mut self) {
        let mut msg = MenuEntrySeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { visualization_msgs__msg__MenuEntry__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for MenuEntrySeq<N> {}
unsafe impl<const N: usize> Sync for MenuEntrySeq<N> {}


impl TypeSupport for MenuEntry {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__visualization_msgs__msg__MenuEntry()
        }
    }
}

impl PartialEq for MenuEntry {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            visualization_msgs__msg__MenuEntry__are_equal(self, other)
        }
    }
}

impl<const N: usize> PartialEq for MenuEntrySeq<N> {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            let msg1 = MenuEntrySeqRaw{data: self.data, size: self.size, capacity: self.capacity};
            let msg2 = MenuEntrySeqRaw{data: other.data, size: other.size, capacity: other.capacity};
            visualization_msgs__msg__MenuEntry__Sequence__are_equal(&msg1, &msg2)
        }
    }
}

