// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;

extern "C" {
    fn sensor_msgs__msg__JoyFeedbackArray__init(msg: *mut JoyFeedbackArray) -> bool;
    fn sensor_msgs__msg__JoyFeedbackArray__fini(msg: *mut JoyFeedbackArray);
    fn sensor_msgs__msg__JoyFeedbackArray__Sequence__init(msg: *mut JoyFeedbackArraySequence, size: usize) -> bool;
    fn sensor_msgs__msg__JoyFeedbackArray__Sequence__fini(msg: *mut JoyFeedbackArraySequence);
}


#[repr(C)]
#[derive(Debug)]
pub struct JoyFeedbackArray {
    pub array: super::JoyFeedbackSequence,
}

impl JoyFeedbackArray {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__JoyFeedbackArray__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for JoyFeedbackArray {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__JoyFeedbackArray__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct JoyFeedbackArraySequence {
    data: *mut JoyFeedbackArray,
    size: usize,
    capacity: usize,
}

impl JoyFeedbackArraySequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__JoyFeedbackArray__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[JoyFeedbackArray]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [JoyFeedbackArray]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for JoyFeedbackArraySequence {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__JoyFeedbackArray__Sequence__fini(self) };
    }
}

