//! These files are automatically generated by using [ros2msg_to_rs](https://github.com/tier4/ros2msg_to_rs) and bindgen.
//!
//! # How to generate
//!
//! ## `common_interfaces` and `ros2msg`
//!
//! ```text
//! $ git clone https://github.com/ros2/common_interfaces.git -b galactic
//! $ ros2msg_to_rs --disable-common-interfaces -s crate -i common_interfaces -o {safe_drive}/src/msg/galactic/common_interfaces
//!
//! $ mkdir ros2msg && cd ros2msg
//! $ git clone https://github.com/ros2/unique_identifier_msgs.git -b galactic
//! $ ros2msg_to_rs --disable-common-interfaces -s crate -i . -o {safe_drive}/src/msg/galactic/ros2msg
//! ```
//!
//! ## runtime_c.rs
//!
//! See [Makefile](https://github.com/tier4/safe_drive/blob/main/supplements/bindgen/Makefile) in supplements.

pub mod common_interfaces;
pub mod ros2msg;
mod runtime_c;

pub use ros2msg::*;
pub use runtime_c::*;
