// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;

extern "C" {
    fn geometry_msgs__msg__AccelStamped__init(msg: *mut AccelStamped) -> bool;
    fn geometry_msgs__msg__AccelStamped__fini(msg: *mut AccelStamped);
    fn geometry_msgs__msg__AccelStamped__Sequence__init(msg: *mut AccelStampedSequence, size: usize) -> bool;
    fn geometry_msgs__msg__AccelStamped__Sequence__fini(msg: *mut AccelStampedSequence);
}


#[repr(C)]
#[derive(Debug)]
pub struct AccelStamped {
    pub header: std_msgs::msg::Header,
    pub accel: Accel,
}

impl AccelStamped {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { geometry_msgs__msg__AccelStamped__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for AccelStamped {
    fn drop(&mut self) {
        unsafe { geometry_msgs__msg__AccelStamped__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct AccelStampedSequence {
    data: *mut AccelStamped,
    size: usize,
    capacity: usize,
}

impl AccelStampedSequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { geometry_msgs__msg__AccelStamped__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[AccelStamped]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [AccelStamped]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for AccelStampedSequence {
    fn drop(&mut self) {
        unsafe { geometry_msgs__msg__AccelStamped__Sequence__fini(self) };
    }
}

