// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;

extern "C" {
    fn geometry_msgs__msg__PoseWithCovarianceStamped__init(msg: *mut PoseWithCovarianceStamped) -> bool;
    fn geometry_msgs__msg__PoseWithCovarianceStamped__fini(msg: *mut PoseWithCovarianceStamped);
    fn geometry_msgs__msg__PoseWithCovarianceStamped__Sequence__init(msg: *mut PoseWithCovarianceStampedSequence, size: usize) -> bool;
    fn geometry_msgs__msg__PoseWithCovarianceStamped__Sequence__fini(msg: *mut PoseWithCovarianceStampedSequence);
}


#[repr(C)]
#[derive(Debug)]
pub struct PoseWithCovarianceStamped {
    pub header: std_msgs::msg::Header,
    pub pose: PoseWithCovariance,
}

impl PoseWithCovarianceStamped {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { geometry_msgs__msg__PoseWithCovarianceStamped__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for PoseWithCovarianceStamped {
    fn drop(&mut self) {
        unsafe { geometry_msgs__msg__PoseWithCovarianceStamped__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct PoseWithCovarianceStampedSequence {
    data: *mut PoseWithCovarianceStamped,
    size: usize,
    capacity: usize,
}

impl PoseWithCovarianceStampedSequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { geometry_msgs__msg__PoseWithCovarianceStamped__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[PoseWithCovarianceStamped]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [PoseWithCovarianceStamped]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for PoseWithCovarianceStampedSequence {
    fn drop(&mut self) {
        unsafe { geometry_msgs__msg__PoseWithCovarianceStamped__Sequence__fini(self) };
    }
}

