// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;

extern "C" {
    fn geometry_msgs__msg__TransformStamped__init(msg: *mut TransformStamped) -> bool;
    fn geometry_msgs__msg__TransformStamped__fini(msg: *mut TransformStamped);
    fn geometry_msgs__msg__TransformStamped__Sequence__init(msg: *mut TransformStampedSequence, size: usize) -> bool;
    fn geometry_msgs__msg__TransformStamped__Sequence__fini(msg: *mut TransformStampedSequence);
    fn rosidl_typesupport_c__get_message_type_support_handle__geometry_msgs__msg__TransformStamped() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct TransformStamped {
    pub header: std_msgs::msg::Header,
    pub child_frame_id: crate::msg::RosString<0>,
    pub transform: Transform,
}

impl TransformStamped {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { geometry_msgs__msg__TransformStamped__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for TransformStamped {
    fn drop(&mut self) {
        unsafe { geometry_msgs__msg__TransformStamped__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct TransformStampedSequence {
    data: *mut TransformStamped,
    size: usize,
    capacity: usize,
}

impl TransformStampedSequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { geometry_msgs__msg__TransformStamped__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[TransformStamped]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [TransformStamped]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for TransformStampedSequence {
    fn drop(&mut self) {
        unsafe { geometry_msgs__msg__TransformStamped__Sequence__fini(self) };
    }
}

unsafe impl Send for TransformStampedSequence {}
unsafe impl Sync for TransformStampedSequence {}


impl TopicMsg for TransformStamped {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__geometry_msgs__msg__TransformStamped()
        }
    }
}
