// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;

extern "C" {
    fn std_msgs__msg__Bool__init(msg: *mut Bool) -> bool;
    fn std_msgs__msg__Bool__fini(msg: *mut Bool);
    fn std_msgs__msg__Bool__Sequence__init(msg: *mut BoolSequence, size: usize) -> bool;
    fn std_msgs__msg__Bool__Sequence__fini(msg: *mut BoolSequence);
}


#[repr(C)]
#[derive(Debug)]
pub struct Bool {
    pub data: bool,
}

impl Bool {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { std_msgs__msg__Bool__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for Bool {
    fn drop(&mut self) {
        unsafe { std_msgs__msg__Bool__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct BoolSequence {
    data: *mut Bool,
    size: usize,
    capacity: usize,
}

impl BoolSequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { std_msgs__msg__Bool__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[Bool]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [Bool]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for BoolSequence {
    fn drop(&mut self) {
        unsafe { std_msgs__msg__Bool__Sequence__fini(self) };
    }
}

