// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;

extern "C" {
    fn sensor_msgs__msg__Temperature__init(msg: *mut Temperature) -> bool;
    fn sensor_msgs__msg__Temperature__fini(msg: *mut Temperature);
    fn sensor_msgs__msg__Temperature__are_equal(lhs: *const Temperature, rhs: *const Temperature) -> bool;
    fn sensor_msgs__msg__Temperature__Sequence__init(msg: *mut TemperatureSeqRaw, size: usize) -> bool;
    fn sensor_msgs__msg__Temperature__Sequence__fini(msg: *mut TemperatureSeqRaw);
    fn sensor_msgs__msg__Temperature__Sequence__are_equal(lhs: *const TemperatureSeqRaw, rhs: *const TemperatureSeqRaw) -> bool;
    fn rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__Temperature() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct Temperature {
    pub header: std_msgs::msg::Header,
    pub temperature: f64,
    pub variance: f64,
}

impl Temperature {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__Temperature__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for Temperature {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__Temperature__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct TemperatureSeqRaw {
    data: *mut Temperature,
    size: usize,
    capacity: usize,
}

/// Sequence of Temperature.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct TemperatureSeq<const N: usize> {
    data: *mut Temperature,
    size: usize,
    capacity: usize,
}

impl<const N: usize> TemperatureSeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: TemperatureSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__Temperature__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn null() -> Self {
        let msg: TemperatureSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        Self {data: msg.data, size: msg.size, capacity: msg.capacity }
    }

    pub fn as_slice(&self) -> &[Temperature] {
        if self.data.is_null() {
            &[]
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            s
        }
    }

    pub fn as_slice_mut(&mut self) -> &mut [Temperature] {
        if self.data.is_null() {
            &mut []
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            s
        }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, Temperature> {
        self.as_slice().iter()
    }

    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, Temperature> {
        self.as_slice_mut().iter_mut()
    }

    pub fn len(&self) -> usize {
        self.as_slice().len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<const N: usize> Drop for TemperatureSeq<N> {
    fn drop(&mut self) {
        let mut msg = TemperatureSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { sensor_msgs__msg__Temperature__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for TemperatureSeq<N> {}
unsafe impl<const N: usize> Sync for TemperatureSeq<N> {}


impl TypeSupport for Temperature {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__Temperature()
        }
    }
}

impl PartialEq for Temperature {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            sensor_msgs__msg__Temperature__are_equal(self, other)
        }
    }
}

impl<const N: usize> PartialEq for TemperatureSeq<N> {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            let msg1 = TemperatureSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
            let msg2 = TemperatureSeqRaw{data: other.data, size: other.size, capacity: other.capacity};
            sensor_msgs__msg__Temperature__Sequence__are_equal(&msg1, &msg2)
        }
    }
}

