// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;

extern "C" {
    fn sensor_msgs__msg__ChannelFloat32__init(msg: *mut ChannelFloat32) -> bool;
    fn sensor_msgs__msg__ChannelFloat32__fini(msg: *mut ChannelFloat32);
    fn sensor_msgs__msg__ChannelFloat32__Sequence__init(msg: *mut ChannelFloat32Sequence, size: usize) -> bool;
    fn sensor_msgs__msg__ChannelFloat32__Sequence__fini(msg: *mut ChannelFloat32Sequence);
    fn rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__ChannelFloat32() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct ChannelFloat32 {
    pub name: crate::msg::RosString<0>,
    pub values: crate::msg::F32Seq<0>,
}

impl ChannelFloat32 {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__ChannelFloat32__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for ChannelFloat32 {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__ChannelFloat32__fini(self) };
    }
}

impl TopicMsg for ChannelFloat32 {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__ChannelFloat32()
        }
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct ChannelFloat32Sequence {
    data: *mut ChannelFloat32,
    size: usize,
    capacity: usize,
}

impl ChannelFloat32Sequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__ChannelFloat32__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[ChannelFloat32]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [ChannelFloat32]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for ChannelFloat32Sequence {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__ChannelFloat32__Sequence__fini(self) };
    }
}

