// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;

extern "C" {
    fn sensor_msgs__msg__Image__init(msg: *mut Image) -> bool;
    fn sensor_msgs__msg__Image__fini(msg: *mut Image);
    fn sensor_msgs__msg__Image__Sequence__init(msg: *mut ImageSequence, size: usize) -> bool;
    fn sensor_msgs__msg__Image__Sequence__fini(msg: *mut ImageSequence);
    fn rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__Image() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct Image {
    pub header: std_msgs::msg::Header,
    pub height: u32,
    pub width: u32,
    pub encoding: crate::msg::RosString<0>,
    pub is_bigendian: u8,
    pub step: u32,
    pub data: crate::msg::U8Seq<0>,
}

impl Image {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__Image__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for Image {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__Image__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct ImageSequence {
    data: *mut Image,
    size: usize,
    capacity: usize,
}

impl ImageSequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__Image__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[Image]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [Image]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for ImageSequence {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__Image__Sequence__fini(self) };
    }
}

unsafe impl Send for ImageSequence {}
unsafe impl Sync for ImageSequence {}


impl TopicMsg for Image {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__Image()
        }
    }
}
