// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;

extern "C" {
    fn sensor_msgs__msg__RegionOfInterest__init(msg: *mut RegionOfInterest) -> bool;
    fn sensor_msgs__msg__RegionOfInterest__fini(msg: *mut RegionOfInterest);
    fn sensor_msgs__msg__RegionOfInterest__Sequence__init(msg: *mut RegionOfInterestSequence, size: usize) -> bool;
    fn sensor_msgs__msg__RegionOfInterest__Sequence__fini(msg: *mut RegionOfInterestSequence);
}


#[repr(C)]
#[derive(Debug)]
pub struct RegionOfInterest {
    pub x_offset: u32,
    pub y_offset: u32,
    pub height: u32,
    pub width: u32,
    pub do_rectify: bool,
}

impl RegionOfInterest {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__RegionOfInterest__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for RegionOfInterest {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__RegionOfInterest__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct RegionOfInterestSequence {
    data: *mut RegionOfInterest,
    size: usize,
    capacity: usize,
}

impl RegionOfInterestSequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__RegionOfInterest__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[RegionOfInterest]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [RegionOfInterest]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for RegionOfInterestSequence {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__RegionOfInterest__Sequence__fini(self) };
    }
}

