// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;

extern "C" {
    fn sensor_msgs__msg__RelativeHumidity__init(msg: *mut RelativeHumidity) -> bool;
    fn sensor_msgs__msg__RelativeHumidity__fini(msg: *mut RelativeHumidity);
    fn sensor_msgs__msg__RelativeHumidity__Sequence__init(msg: *mut RelativeHumiditySeqRaw, size: usize) -> bool;
    fn sensor_msgs__msg__RelativeHumidity__Sequence__fini(msg: *mut RelativeHumiditySeqRaw);
    fn rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__RelativeHumidity() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct RelativeHumidity {
    pub header: std_msgs::msg::Header,
    pub relative_humidity: f64,
    pub variance: f64,
}

impl RelativeHumidity {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__RelativeHumidity__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for RelativeHumidity {
    fn drop(&mut self) {
        unsafe { sensor_msgs__msg__RelativeHumidity__fini(self) };
    }
}


struct RelativeHumiditySeqRaw {
    data: *mut RelativeHumidity,
    size: usize,
    capacity: usize,
}

/// Sequence of RelativeHumidity.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct RelativeHumiditySeq<const N: usize> {
    data: *mut RelativeHumidity,
    size: usize,
    capacity: usize,
}

impl<const N: usize> RelativeHumiditySeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: RelativeHumiditySeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { sensor_msgs__msg__RelativeHumidity__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[RelativeHumidity]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [RelativeHumidity]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl<const N: usize> Drop for RelativeHumiditySeq<N> {
    fn drop(&mut self) {
        let mut msg = RelativeHumiditySeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { sensor_msgs__msg__RelativeHumidity__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for RelativeHumiditySeq<N> {}
unsafe impl<const N: usize> Sync for RelativeHumiditySeq<N> {}


impl TopicMsg for RelativeHumidity {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__RelativeHumidity()
        }
    }
}
