#include <std_msgs/msg/bool.h>
#include <std_msgs/msg/byte.h>
#include <std_msgs/msg/byte_multi_array.h>
#include <std_msgs/msg/char.h>
#include <std_msgs/msg/color_rgba.h>
#include <std_msgs/msg/empty.h>
#include <std_msgs/msg/float32.h>
#include <std_msgs/msg/float32_multi_array.h>
#include <std_msgs/msg/float64.h>
#include <std_msgs/msg/float64_multi_array.h>
#include <std_msgs/msg/header.h>
#include <std_msgs/msg/int8_multi_array.h>
#include <std_msgs/msg/int16_multi_array.h>
#include <std_msgs/msg/int32_multi_array.h>
#include <std_msgs/msg/int64_multi_array.h>
#include <std_msgs/msg/u_int8_multi_array.h>
#include <std_msgs/msg/u_int16_multi_array.h>
#include <std_msgs/msg/u_int32_multi_array.h>
#include <std_msgs/msg/u_int64_multi_array.h>
#include <std_msgs/msg/string.h>
