# http://wiki.ros.org/msg
bool a
int8 b
uint8 c
int16 d
uint16 e
int32 f
uint32 g
int64 h
uint64 i
float32 j
float64 k
string l
# time m
# duration n

# array
int32[] o
int32[10] p

# http://wiki.ros.org/std_msgs
std_msgs/Bool q
std_msgs/Byte r
std_msgs/ByteMultiArray s
std_msgs/Char t
std_msgs/ColorRGBA u
# std_msgs/Duration v
std_msgs/Empty w
std_msgs/Float32 x
std_msgs/Float32MultiArray y
std_msgs/Float64 z
std_msgs/Float64MultiArray aa
std_msgs/Header bb
std_msgs/Int16 cc
std_msgs/Int16MultiArray dd
std_msgs/Int32 ee
std_msgs/Int32MultiArray ff
std_msgs/Int64 gg
std_msgs/Int64MultiArray hh
std_msgs/Int8 ii
std_msgs/Int8MultiArray jj
std_msgs/MultiArrayDimension kk
std_msgs/MultiArrayLayout ll
std_msgs/String mm
# std_msgs/Time nn
std_msgs/UInt16 oo
std_msgs/UInt16MultiArray pp
std_msgs/UInt32 qq
std_msgs/UInt32MultiArray rr
std_msgs/UInt64 ss
std_msgs/UInt64MultiArray tt
std_msgs/UInt8 uu
std_msgs/UInt8MultiArray vv
