// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;
pub const LOG_LEVEL_UNKNOWN: u8 = 0;
pub const LOG_LEVEL_DEBUG: u8 = 10;
pub const LOG_LEVEL_INFO: u8 = 20;
pub const LOG_LEVEL_WARN: u8 = 30;
pub const LOG_LEVEL_ERROR: u8 = 40;
pub const LOG_LEVEL_FATAL: u8 = 50;

extern "C" {
    fn rcl_interfaces__msg__LoggerLevel__init(msg: *mut LoggerLevel) -> bool;
    fn rcl_interfaces__msg__LoggerLevel__fini(msg: *mut LoggerLevel);
    fn rcl_interfaces__msg__LoggerLevel__are_equal(lhs: *const LoggerLevel, rhs: *const LoggerLevel) -> bool;
    fn rcl_interfaces__msg__LoggerLevel__Sequence__init(msg: *mut LoggerLevelSeqRaw, size: usize) -> bool;
    fn rcl_interfaces__msg__LoggerLevel__Sequence__fini(msg: *mut LoggerLevelSeqRaw);
    fn rcl_interfaces__msg__LoggerLevel__Sequence__are_equal(lhs: *const LoggerLevelSeqRaw, rhs: *const LoggerLevelSeqRaw) -> bool;
    fn rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__msg__LoggerLevel() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct LoggerLevel {
    pub name: crate::msg::RosString<0>,
    pub level: u32,
}

impl LoggerLevel {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { rcl_interfaces__msg__LoggerLevel__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for LoggerLevel {
    fn drop(&mut self) {
        unsafe { rcl_interfaces__msg__LoggerLevel__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct LoggerLevelSeqRaw {
    data: *mut LoggerLevel,
    size: size_t,
    capacity: size_t,
}

/// Sequence of LoggerLevel.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct LoggerLevelSeq<const N: usize> {
    data: *mut LoggerLevel,
    size: size_t,
    capacity: size_t,
}

impl<const N: usize> LoggerLevelSeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size > N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: LoggerLevelSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { rcl_interfaces__msg__LoggerLevel__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn null() -> Self {
        let msg: LoggerLevelSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        Self {data: msg.data, size: msg.size, capacity: msg.capacity }
    }

    pub fn as_slice(&self) -> &[LoggerLevel] {
        if self.data.is_null() {
            &[]
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size as _) };
            s
        }
    }

    pub fn as_slice_mut(&mut self) -> &mut [LoggerLevel] {
        if self.data.is_null() {
            &mut []
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size as _) };
            s
        }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, LoggerLevel> {
        self.as_slice().iter()
    }

    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, LoggerLevel> {
        self.as_slice_mut().iter_mut()
    }

    pub fn len(&self) -> usize {
        self.as_slice().len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<const N: usize> Drop for LoggerLevelSeq<N> {
    fn drop(&mut self) {
        let mut msg = LoggerLevelSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { rcl_interfaces__msg__LoggerLevel__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for LoggerLevelSeq<N> {}
unsafe impl<const N: usize> Sync for LoggerLevelSeq<N> {}


impl TypeSupport for LoggerLevel {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__msg__LoggerLevel()
        }
    }
}

impl PartialEq for LoggerLevel {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            rcl_interfaces__msg__LoggerLevel__are_equal(self, other)
        }
    }
}

impl<const N: usize> PartialEq for LoggerLevelSeq<N> {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            let msg1 = LoggerLevelSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
            let msg2 = LoggerLevelSeqRaw{data: other.data, size: other.size, capacity: other.capacity};
            rcl_interfaces__msg__LoggerLevel__Sequence__are_equal(&msg1, &msg2)
        }
    }
}

