// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;

extern "C" {
    fn visualization_msgs__msg__InteractiveMarkerPose__init(msg: *mut InteractiveMarkerPose) -> bool;
    fn visualization_msgs__msg__InteractiveMarkerPose__fini(msg: *mut InteractiveMarkerPose);
    fn visualization_msgs__msg__InteractiveMarkerPose__Sequence__init(msg: *mut InteractiveMarkerPoseSeqRaw, size: usize) -> bool;
    fn visualization_msgs__msg__InteractiveMarkerPose__Sequence__fini(msg: *mut InteractiveMarkerPoseSeqRaw);
    fn rosidl_typesupport_c__get_message_type_support_handle__visualization_msgs__msg__InteractiveMarkerPose() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct InteractiveMarkerPose {
    pub header: std_msgs::msg::Header,
    pub pose: geometry_msgs::msg::Pose,
    pub name: crate::msg::RosString<0>,
}

impl InteractiveMarkerPose {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { visualization_msgs__msg__InteractiveMarkerPose__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for InteractiveMarkerPose {
    fn drop(&mut self) {
        unsafe { visualization_msgs__msg__InteractiveMarkerPose__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct InteractiveMarkerPoseSeqRaw {
    data: *mut InteractiveMarkerPose,
    size: usize,
    capacity: usize,
}

/// Sequence of InteractiveMarkerPose.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct InteractiveMarkerPoseSeq<const N: usize> {
    data: *mut InteractiveMarkerPose,
    size: usize,
    capacity: usize,
}

impl<const N: usize> InteractiveMarkerPoseSeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: InteractiveMarkerPoseSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { visualization_msgs__msg__InteractiveMarkerPose__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[InteractiveMarkerPose]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [InteractiveMarkerPose]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl<const N: usize> Drop for InteractiveMarkerPoseSeq<N> {
    fn drop(&mut self) {
        let mut msg = InteractiveMarkerPoseSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { visualization_msgs__msg__InteractiveMarkerPose__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for InteractiveMarkerPoseSeq<N> {}
unsafe impl<const N: usize> Sync for InteractiveMarkerPoseSeq<N> {}


impl TopicMsg for InteractiveMarkerPose {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__visualization_msgs__msg__InteractiveMarkerPose()
        }
    }
}
