// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::super::super::*;
use super::*;
use crate::msg::*;
use crate::rcl;

extern "C" {
    fn lifecycle_msgs__msg__TransitionDescription__init(msg: *mut TransitionDescription) -> bool;
    fn lifecycle_msgs__msg__TransitionDescription__fini(msg: *mut TransitionDescription);
    fn lifecycle_msgs__msg__TransitionDescription__are_equal(
        lhs: *const TransitionDescription,
        rhs: *const TransitionDescription,
    ) -> bool;
    fn lifecycle_msgs__msg__TransitionDescription__Sequence__init(
        msg: *mut TransitionDescriptionSeqRaw,
        size: usize,
    ) -> bool;
    fn lifecycle_msgs__msg__TransitionDescription__Sequence__fini(
        msg: *mut TransitionDescriptionSeqRaw,
    );
    fn lifecycle_msgs__msg__TransitionDescription__Sequence__are_equal(
        lhs: *const TransitionDescriptionSeqRaw,
        rhs: *const TransitionDescriptionSeqRaw,
    ) -> bool;
    fn rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__msg__TransitionDescription(
    ) -> *const rcl::rosidl_message_type_support_t;
}

#[repr(C)]
#[derive(Debug)]
pub struct TransitionDescription {
    pub transition: Transition,
    pub start_state: State,
    pub goal_state: State,
}

impl TransitionDescription {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { lifecycle_msgs__msg__TransitionDescription__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for TransitionDescription {
    fn drop(&mut self) {
        unsafe { lifecycle_msgs__msg__TransitionDescription__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct TransitionDescriptionSeqRaw {
    data: *mut TransitionDescription,
    size: usize,
    capacity: usize,
}

/// Sequence of TransitionDescription.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct TransitionDescriptionSeq<const N: usize> {
    data: *mut TransitionDescription,
    size: usize,
    capacity: usize,
}

impl<const N: usize> TransitionDescriptionSeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: TransitionDescriptionSeqRaw =
            unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { lifecycle_msgs__msg__TransitionDescription__Sequence__init(&mut msg, size) } {
            Some(Self {
                data: msg.data,
                size: msg.size,
                capacity: msg.capacity,
            })
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> &[TransitionDescription] {
        if self.data.is_null() {
            &[]
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            s
        }
    }

    pub fn as_slice_mut(&mut self) -> &mut [TransitionDescription] {
        if self.data.is_null() {
            &mut []
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            s
        }
    }
}

impl<const N: usize> Drop for TransitionDescriptionSeq<N> {
    fn drop(&mut self) {
        let mut msg = TransitionDescriptionSeqRaw {
            data: self.data,
            size: self.size,
            capacity: self.capacity,
        };
        unsafe { lifecycle_msgs__msg__TransitionDescription__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for TransitionDescriptionSeq<N> {}
unsafe impl<const N: usize> Sync for TransitionDescriptionSeq<N> {}

impl TopicMsg for TransitionDescription {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__msg__TransitionDescription()
        }
    }
}

impl PartialEq for TransitionDescription {
    fn eq(&self, other: &Self) -> bool {
        unsafe { lifecycle_msgs__msg__TransitionDescription__are_equal(self, other) }
    }
}

impl<const N: usize> PartialEq for TransitionDescriptionSeq<N> {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            let msg1 = TransitionDescriptionSeqRaw {
                data: self.data,
                size: self.size,
                capacity: self.capacity,
            };
            let msg2 = TransitionDescriptionSeqRaw {
                data: other.data,
                size: other.size,
                capacity: other.capacity,
            };
            lifecycle_msgs__msg__TransitionDescription__Sequence__are_equal(&msg1, &msg2)
        }
    }
}
