// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;

extern "C" {
    fn rcl_interfaces__msg__ParameterValue__init(msg: *mut ParameterValue) -> bool;
    fn rcl_interfaces__msg__ParameterValue__fini(msg: *mut ParameterValue);
    fn rcl_interfaces__msg__ParameterValue__are_equal(lhs: *const ParameterValue, rhs: *const ParameterValue) -> bool;
    fn rcl_interfaces__msg__ParameterValue__Sequence__init(msg: *mut ParameterValueSeqRaw, size: usize) -> bool;
    fn rcl_interfaces__msg__ParameterValue__Sequence__fini(msg: *mut ParameterValueSeqRaw);
    fn rcl_interfaces__msg__ParameterValue__Sequence__are_equal(lhs: *const ParameterValueSeqRaw, rhs: *const ParameterValueSeqRaw) -> bool;
    fn rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__msg__ParameterValue() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct ParameterValue {
    pub type_: u8,
    pub bool_value: bool,
    pub integer_value: i64,
    pub double_value: f64,
    pub string_value: crate::msg::RosString<0>,
    pub byte_array_value: crate::msg::U8Seq<0>,
    pub bool_array_value: crate::msg::BoolSeq<0>,
    pub integer_array_value: crate::msg::I64Seq<0>,
    pub double_array_value: crate::msg::F64Seq<0>,
    pub string_array_value: crate::msg::RosStringSeq<0, 0>,
}

impl ParameterValue {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { rcl_interfaces__msg__ParameterValue__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for ParameterValue {
    fn drop(&mut self) {
        unsafe { rcl_interfaces__msg__ParameterValue__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct ParameterValueSeqRaw {
    data: *mut ParameterValue,
    size: usize,
    capacity: usize,
}

/// Sequence of ParameterValue.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct ParameterValueSeq<const N: usize> {
    data: *mut ParameterValue,
    size: usize,
    capacity: usize,
}

impl<const N: usize> ParameterValueSeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: ParameterValueSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { rcl_interfaces__msg__ParameterValue__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn null() -> Self {
        let msg: ParameterValueSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        Self {data: msg.data, size: msg.size, capacity: msg.capacity }
    }

    pub fn as_slice(&self) -> &[ParameterValue] {
        if self.data.is_null() {
            &[]
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            s
        }
    }

    pub fn as_slice_mut(&mut self) -> &mut [ParameterValue] {
        if self.data.is_null() {
            &mut []
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            s
        }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, ParameterValue> {
        self.as_slice().iter()
    }

    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, ParameterValue> {
        self.as_slice_mut().iter_mut()
    }

    pub fn len(&self) -> usize {
        self.as_slice().len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<const N: usize> Drop for ParameterValueSeq<N> {
    fn drop(&mut self) {
        let mut msg = ParameterValueSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { rcl_interfaces__msg__ParameterValue__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for ParameterValueSeq<N> {}
unsafe impl<const N: usize> Sync for ParameterValueSeq<N> {}


impl TypeSupport for ParameterValue {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__msg__ParameterValue()
        }
    }
}

impl PartialEq for ParameterValue {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            rcl_interfaces__msg__ParameterValue__are_equal(self, other)
        }
    }
}

impl<const N: usize> PartialEq for ParameterValueSeq<N> {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            let msg1 = ParameterValueSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
            let msg2 = ParameterValueSeqRaw{data: other.data, size: other.size, capacity: other.capacity};
            rcl_interfaces__msg__ParameterValue__Sequence__are_equal(&msg1, &msg2)
        }
    }
}

