// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;
use crate::rcl;
pub const PRIMARY_STATE_UNKNOWN: u8 = 0;
pub const PRIMARY_STATE_UNCONFIGURED: u8 = 1;
pub const PRIMARY_STATE_INACTIVE: u8 = 2;
pub const PRIMARY_STATE_ACTIVE: u8 = 3;
pub const PRIMARY_STATE_FINALIZED: u8 = 4;
pub const TRANSITION_STATE_CONFIGURING: u8 = 10;
pub const TRANSITION_STATE_CLEANINGUP: u8 = 11;
pub const TRANSITION_STATE_SHUTTINGDOWN: u8 = 12;
pub const TRANSITION_STATE_ACTIVATING: u8 = 13;
pub const TRANSITION_STATE_DEACTIVATING: u8 = 14;
pub const TRANSITION_STATE_ERRORPROCESSING: u8 = 15;

extern "C" {
    fn lifecycle_msgs__msg__State__init(msg: *mut State) -> bool;
    fn lifecycle_msgs__msg__State__fini(msg: *mut State);
    fn lifecycle_msgs__msg__State__are_equal(lhs: *const State, rhs: *const State) -> bool;
    fn lifecycle_msgs__msg__State__Sequence__init(msg: *mut StateSeqRaw, size: usize) -> bool;
    fn lifecycle_msgs__msg__State__Sequence__fini(msg: *mut StateSeqRaw);
    fn lifecycle_msgs__msg__State__Sequence__are_equal(lhs: *const StateSeqRaw, rhs: *const StateSeqRaw) -> bool;
    fn rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__msg__State() -> *const rcl::rosidl_message_type_support_t;
}


#[repr(C)]
#[derive(Debug)]
pub struct State {
    pub id: u8,
    pub label: crate::msg::RosString<0>,
}

impl State {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { lifecycle_msgs__msg__State__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for State {
    fn drop(&mut self) {
        unsafe { lifecycle_msgs__msg__State__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
struct StateSeqRaw {
    data: *mut State,
    size: usize,
    capacity: usize,
}

/// Sequence of State.
/// `N` is the maximum number of elements.
/// If `N` is `0`, the size is unlimited.
#[repr(C)]
#[derive(Debug)]
pub struct StateSeq<const N: usize> {
    data: *mut State,
    size: usize,
    capacity: usize,
}

impl<const N: usize> StateSeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }

        let mut msg: StateSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { lifecycle_msgs__msg__State__Sequence__init(&mut msg, size) } {
            Some(Self {data: msg.data, size: msg.size, capacity: msg.capacity })
        } else {
            None
        }
    }

    pub fn null() -> Self {
        let msg: StateSeqRaw = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        Self {data: msg.data, size: msg.size, capacity: msg.capacity }
    }

    pub fn as_slice(&self) -> &[State] {
        if self.data.is_null() {
            &[]
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            s
        }
    }

    pub fn as_slice_mut(&mut self) -> &mut [State] {
        if self.data.is_null() {
            &mut []
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            s
        }
    }

    pub fn iter(&self) -> std::slice::Iter<'_, State> {
        self.as_slice().iter()
    }

    pub fn iter_mut(&mut self) -> std::slice::IterMut<'_, State> {
        self.as_slice_mut().iter_mut()
    }

    pub fn len(&self) -> usize {
        self.as_slice().len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<const N: usize> Drop for StateSeq<N> {
    fn drop(&mut self) {
        let mut msg = StateSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
        unsafe { lifecycle_msgs__msg__State__Sequence__fini(&mut msg) };
    }
}

unsafe impl<const N: usize> Send for StateSeq<N> {}
unsafe impl<const N: usize> Sync for StateSeq<N> {}


impl TypeSupport for State {
    fn type_support() -> *const rcl::rosidl_message_type_support_t {
        unsafe {
            rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__msg__State()
        }
    }
}

impl PartialEq for State {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            lifecycle_msgs__msg__State__are_equal(self, other)
        }
    }
}

impl<const N: usize> PartialEq for StateSeq<N> {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            let msg1 = StateSeqRaw{data: self.data, size: self.size, capacity: self.capacity};
            let msg2 = StateSeqRaw{data: other.data, size: other.size, capacity: other.capacity};
            lifecycle_msgs__msg__State__Sequence__are_equal(&msg1, &msg2)
        }
    }
}

