// This file was automatically generated by ros2msg_to_rs (https://github.com/tier4/ros2msg_to_rs).
use super::*;
use super::super::super::*;
use crate::msg::*;

extern "C" {
    fn std_msgs__msg__String__init(msg: *mut String) -> bool;
    fn std_msgs__msg__String__fini(msg: *mut String);
    fn std_msgs__msg__String__Sequence__init(msg: *mut StringSequence, size: usize) -> bool;
    fn std_msgs__msg__String__Sequence__fini(msg: *mut StringSequence);
}


#[repr(C)]
#[derive(Debug)]
pub struct String {
    pub data: crate::msg::RosString<0>,
}

impl String {
    pub fn new() -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { std_msgs__msg__String__init(&mut msg) } {
            Some(msg)
        } else {
            None
        }
    }
}

impl Drop for String {
    fn drop(&mut self) {
        unsafe { std_msgs__msg__String__fini(self) };
    }
}

#[repr(C)]
#[derive(Debug)]
pub struct StringSequence {
    data: *mut String,
    size: usize,
    capacity: usize,
}

impl StringSequence {
    pub fn new(size: usize) -> Option<Self> {
        let mut msg: Self = unsafe { std::mem::MaybeUninit::zeroed().assume_init() };
        if unsafe { std_msgs__msg__String__Sequence__init(&mut msg, size) } {
            Some(msg)
        } else {
            None
        }
    }

    pub fn as_slice(&self) -> Option<&[String]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts(self.data, self.size) };
            Some(s)
        }
    }

    pub fn as_slice_mut(&mut self) -> Option<&mut [String]> {
        if self.data.is_null() {
            None
        } else {
            let s = unsafe { std::slice::from_raw_parts_mut(self.data, self.size) };
            Some(s)
        }
    }
}

impl Drop for StringSequence {
    fn drop(&mut self) {
        unsafe { std_msgs__msg__String__Sequence__fini(self) };
    }
}

